[package]
name = "ocypus-l24-digital"
version = "0.1.0"
edition = "2024"

[dependencies]
hidapi = { version = "2.6.3" }
systemstat = "0.2.5"
log = "0.4"
env_logger = "0.11"
clap = { version = "4.5", features = ["derive"] }
