[package]
name = "ocypus-l24-digital"
version = "0.2.0"
edition = "2024"

[dependencies]
hidapi = { version = "2.6.4" }
log = "0.4.29"
env_logger = "0.11"
clap = { version = "4.5", features = ["derive"] }
regex = "1.12.2"
